version: '3'

services:
    mysql:
      image: mysql:debian
      container_name: mysql
      hostname: $DBHOST
      volumes:
        - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
        - ./mysql/data:/var/lib/mysql
      command: --default-authentication-plugin=mysql_native_password
      environment:
        MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
        MYSQL_DATABASE: $MYSQL_DATABASE
        MYSQL_USER: $MYSQL_USER
        MYSQL_PASSWORD: $MYSQL_PASSWORD
      healthcheck:
       test: "mysql -u$MYSQL_USER -p$MYSQL_PASSWORD -e ';'"
      networks:
        - urlsh
      restart: always

    go:
      build: go
      image: go
      container_name: go
      hostname: go
      ports:
        - 8080:8080
      environment:
        MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
        MYSQL_DATABASE: $MYSQL_DATABASE
        MYSQL_USER: $MYSQL_USER
        MYSQL_PASSWORD: $MYSQL_PASSWORD
        DBHOST: $DBHOST
      depends_on:
        mysql:
          condition: service_healthy
      networks:
        - urlsh
      restart: always

networks:
  urlsh:
    {}
