FROM golang:1.18-alpine

RUN apk update && apk add mysql mysql-client

WORKDIR /go/src

COPY . /go/src
RUN go env -w GO111MODULE=auto
RUN go build -v -o $GOPATH/bin/url_shortener server.go resolve.go

CMD [ "url_shortener" ]
