FROM golang:1.18-alpine

WORKDIR /go/src

COPY . /go/src
RUN go env -w GO111MODULE=auto
# RUN go mod init
RUN go build -v -o $GOPATH/bin/url_shortener server.go resolve.go

CMD [ "url_shortener" ]
# CMD [ "sh" ]
